### ISSUE TITLE
Fix `import/no-unresolved` for uppy lerna packages

### ISSUE THREAD

**Issue by Murderlon** [transloadit/eslint-config-transloadit#10]
A quick cmd + f search in the terminal output shows about 356 warnings for `import/no-unresolved` due to uppy packages. This is a quick win to get rid of a lot of warnings. 

<img width="1095" alt="Screenshot 2021-06-02 at 15 05 30" src="https://user-images.githubusercontent.com/9060226/120486808-ab938200-c3b5-11eb-95de-e19bd10a07b4.png">

Possible solution: https://www.npmjs.com/package/eslint-import-resolver-lerna

**Comment by kvz** [comment]
@mifi might you have a look at this one?

**Comment by Murderlon** [comment]
I also can take a look at it later.

**Comment by kvz** [comment]
Okay Mikael only works a few hours a week and probably has enough on his plate so if you could take a first shot that sounds good :+1: Just ping if it doesn't work out or if you have questions :ok_hand:

**Comment by mifi** [comment]
Sounds great! Just submit a PR or I can do it if you haven't started on it yet.

**Comment by Murderlon** [comment]
@mifi see the link to pull request above your comment. I was thinking the same.

**Comment by Murderlon** [comment]
Fixed in https://github.com/transloadit/uppy/pull/2915
